
### Get all markets
## GET http://localhost:8080/markets
GET https://hackfest-market-manager-git-viada-production.apps.wa6eqszp.uksouth.aroapp.io/markets

### Get single market by id
GET https://hackfest-market-manager-git-viada-production.apps.wa6eqszp.uksouth.aroapp.io/markets/705f92c1-57ab-437f-b6de-eceb38f22d44

### create market
##POST http://localhost:8080/markets
POST https://hackfest-market-manager-git-viada-production.apps.wa6eqszp.uksouth.aroapp.io//markets
Content-Type: application/json

{
  "id": "{{ $random.uuid }}",
  "name": "{{ VIADA Market }}"
}

### subscribe to product events
