
### Get all markets
## GET http://localhost:8080/markets
GET https://hackfest-market-manager-git-viada-production.apps.wa6eqszp.uksouth.aroapp.io/markets

### Get single market by id
GET http://localhost:8080/markets/ad6e6dc4-a3ff-4426-abed-33dff32cb3ba

### create market
##POST http://localhost:8080/markets
POST https://hackfest-market-manager-git-viada-production.apps.wa6eqszp.uksouth.aroapp.io//markets
Content-Type: application/json

{
  "id": "{{ $random.uuid }}",
  "name": "{{ VIADA Market }}"
}

### subscribe to product events
